project:
  type: default

format:
  html:
    webr:
      show-code: false
    theme: journal
    toc: true
    toc-location: right
    toc-expand: 1
    number-sections: true
    css: styles.css

filters:
  - webr

webr:
  packages: [wordcloud , dplyr, ggplot2 , stringr]


